version: '3'
services:
  db:
    image: mysql:5.7
    container_name: sgp-mysql
    environment:
      - MYSQL_DATABASE=sgp
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - '3306:3306'
    network_mode: host
